services:
  checkov:
    image: bridgecrew/checkov:latest
    volumes:
      - ./rules:/rules:ro
      - ../sadcloud/tfvars:/data:ro
      - ./out:/out:rw
      - ./run_checkov_all.sh:/scripts/run_checkov_all.sh:ro
    working_dir: /data
    entrypoint: ["/bin/sh", "-c"]
