services:
  infracost:
    image: infracost/infracost:latest
    entrypoint: ["/bin/sh", "-c"]
    env_file:
      - .env
    environment:
      - INFRACOST_API_KEY
    volumes:
      - ./run_infracost_all.sh:/scripts/run_infracost_all.sh:ro
      - ${TFVARS_DIR:-../../training_set/sadcloud/tfvars}:/data:ro
      - ${OUT_DIR:-../../training_set/infracost/out}:/out:rw
    working_dir: /data
    tty: true
